ExternalProject_Add(
        edtls
        PATCH_COMMAND ""
        UPDATE_COMMAND ""
        DOWNLOAD_COMMAND ""
        SOURCE_DIR "${PROJECT_SOURCE_DIR}/libhuestream/edtls"
        CMAKE_ARGS -DCMAKE_PREFIX_PATH=${CMAKE_BINARY_DIR} -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR} -DBUILD_DTLS_LIB=OFF -DBUILD_TEST=OFF -DBUILD_CLIENT=ON -DBUILD_SERVER=OFF
        TEST_COMMAND ""
)