cmake_minimum_required(VERSION 3.6)

ExternalProject_Add(external_boost
    PREFIX ${EXTERNAL_LIBRARIES_BUILD_PATH}
    URL "${boost_URL}"
    UPDATE_COMMAND ""
    DOWNLOAD_DIR "${EXTERNAL_LIBRARIES_SOURCE_PATH}/boost/src"
    SOURCE_DIR "${EXTERNAL_LIBRARIES_SOURCE_PATH}/boost/src"
    PATCH_COMMAND ${CMAKE_COMMAND} -E copy "${EXTERNAL_LIBRARIES_SOURCE_PATH}/boost/CMakeLists.txt" "${EXTERNAL_LIBRARIES_SOURCE_PATH}/boost/src/CMakeLists.txt"
    CMAKE_ARGS ${COMMON_ARGS} -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD} -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DINSTALL_DESTINATION=include/boost -DCMAKE_PREFIX_PATH=${EXTERNAL_LIBRARIES_INSTALL_PATH} -DCMAKE_INSTALL_PREFIX=${EXTERNAL_LIBRARIES_INSTALL_PATH}
    )

add_library(boost INTERFACE)
target_include_directories(boost INTERFACE ${EXTERNAL_LIBRARIES_INSTALL_PATH}/include)
add_dependencies(boost external_boost)